name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-setup-node-v4-0-4:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      # https://github.com/actions/checkout/releases
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js v4.0.4
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci

  build-setup-node-v4-4-0:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      # https://github.com/actions/checkout/releases
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js v4.4.0
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci
